# Generated by Django 2.1.7 on 2019-03-24 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email address')),
                ('uid', models.CharField(help_text='微信用户绑定和CC视频统计', max_length=64, unique=True)),
                ('mobile', models.BigIntegerField(help_text='用于手机验证码登录', unique=True, verbose_name='手机')),
                ('qq', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='QQ')),
                ('weixin', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='微信')),
                ('signature', models.CharField(blank=True, max_length=255, null=True, verbose_name='个人签名')),
                ('brief', models.TextField(blank=True, null=True, verbose_name='个人介绍')),
                ('openid', models.CharField(blank=True, max_length=128, null=True)),
                ('gender', models.SmallIntegerField(choices=[(0, '保密'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('password', models.CharField(help_text="<a class='btn-link' href='password'>重置密码</a>", max_length=128, verbose_name='password')),
                ('is_active', models.BooleanField(default=True, verbose_name='账户状态')),
                ('is_staff', models.BooleanField(default=False, help_text='决定着用户是否可登录管理后台', verbose_name='staff status')),
                ('name', models.CharField(default='', max_length=32, verbose_name='真实姓名')),
                ('head_img', models.CharField(default='/static/frontend/head_portrait/logo@2x.png', max_length=128, verbose_name='个人头像')),
                ('role', models.SmallIntegerField(choices=[(0, '学员'), (1, '导师'), (2, '讲师'), (3, '管理员')], default=0, verbose_name='角色')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='可提现和使用余额')),
                ('memo', models.TextField(blank=True, default=None, null=True, verbose_name='备注')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name_plural': '1. 账户信息',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('contact', models.CharField(blank=True, max_length=64, null=True)),
                ('feedback_type', models.SmallIntegerField(choices=[(0, '网站优化建议'), (1, '烂!我想吐槽'), (2, '网站bug反馈')])),
                ('content', models.TextField(max_length=1024)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '28. 用户反馈',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.SmallIntegerField(choices=[(0, '文章标签'), (1, '课程评价标签'), (2, '用户感兴趣技术标签')])),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
            ],
            options={
                'verbose_name_plural': '20. Tag标签',
            },
        ),
        migrations.CreateModel(
            name='UserAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Account')),
            ],
            options={
                'verbose_name_plural': '2. 用户Token',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.Tags', verbose_name='感兴趣的标签'),
        ),
    ]
