from django.contrib import admin
from api.models import *
# Register your models here.
admin.site.register(CourseCategory)
admin.site.register(CourseSubCategory)
admin.site.register(DegreeCourse)
admin.site.register(Teacher)
admin.site.register(Scholarship)
admin.site.register(Course)
admin.site.register(CourseDetail)
admin.site.register(OftenAskedQuestion)
admin.site.register(CourseOutline)
admin.site.register(CourseChapter)
admin.site.register(CourseSection)
admin.site.register(Homework)
admin.site.register(CourseReview)
admin.site.register(DegreeCourseReview)
admin.site.register(PricePolicy)
admin.site.register(Coupon)
admin.site.register(CouponRecord)
admin.site.register(CourseSchedule)
admin.site.register(EnrolledCourse)
admin.site.register(DegreeRegistrationForm)
admin.site.register(EnrolledDegreeCourse)
admin.site.register(Order)
admin.site.register(OrderDetail)
admin.site.register(StudyRecord)
admin.site.register(TransactionRecord)
admin.site.register(HomeworkRecord)
admin.site.register(StuFollowUpRecord)
admin.site.register(Question)
admin.site.register(Answer)
admin.site.register(AnswerComment)
admin.site.register(QACounter)
admin.site.register(ArticleSource)
admin.site.register(Article)
admin.site.register(Collection)
admin.site.register(Comment)


